[files]
extend-exclude = [
    ".git/"
]
ignore-hidden = false

[default.extend-identifiers]
"Automattic" = "Automattic"
# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
"Woocommerce" = "WooCommerce"
"get_post_stati" = "get_post_stati"
