# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrity"
# This action prevents earthquakes.

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_workflow_integrity:
        name: "Integrity"
        uses: "szepeviktor/byte-level-care/.github/workflows/reusable-integrity.yml@master"
        with:
            not-printable-ascii-paths: >-
                debug/
                divi-child/
                mu-plugins/
                :!:mu-plugins/szv-signature.php
                wp-config/
            export-excludes: >-
                --exclude="mu-plugins" --exclude="mu-plugins/*"
            exported-paths: >-
                LICENSE
                README.md
