# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrity"
# This action prevents earthquakes.

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_workflow_integrity:
        name: "Integrity"
        uses: "szepeviktor/byte-level-care/.github/workflows/reusable-integrity.yml@master"
        with:
            executables: >-
                check-installation/wp-core-4.9-latest.sh
                check-installation/wp-invalid-character.sh
                check-installation/wp-invalid-lang.sh
                check-installation/wp-invalid-media.sh
                check-installation/wp-missing-cron.sh
                check-installation/wp-nonsilent-indices.sh
            not-printable-ascii-paths: >-
                divi-child/
                mu-plugins/
                :!:mu-plugins/szv-signature.php
                wp-config/
            export-excludes: >-
                --exclude="check-installation" --exclude="check-installation/*"
                --exclude="debug" --exclude="debug/*"
                --exclude="mu-plugins" --exclude="mu-plugins/*"
            exported-paths: >-
                LICENSE
                README.md
